import { CssBaseline } from "@mui/material";
import type { AppProps } from "next/app";
import Head from "next/head";


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Anno's Wedding Kiosk</title>
        <link href="https://fonts.googleapis.com/css2?family=Cute+Font&display=swap" rel="stylesheet" />
      </Head>
      <CssBaseline />
      <div>
        <div className="itemBody">
          <Component {...pageProps} />
        </div>
      </div>

      <style jsx>
        {`
          .itemBody {
            font-family: "Cute Font", sans-serif;
            display: flex;
            flex-direction: column;
            height: 100vh;
          }
        `}
      </style>
    </>
  );
}
