version: "1"
services:
  wedding-backend:
    image: ababqw123/wedding-backend:6e8746a3f88eed421b70246fe061b45c3c03ba74
    ports:
      - 8080:8080
  wedding-frontend:
    image: ababqw123/wedding-frontend:a63397523d71d7361c8b1de7c402e005f11f26fa
    environment:
      - NEXT_PUBLIC_SERVER_URL=wedding-backend-1
      - NEXT_PUBLIC_MAP_TOKEN=8591044f66278fd2484621cb7140724d
    ports:
      - 80:3000
    depends_on:
      - wedding-backend

networks:
  wedding-network:
    driver: bridge
