version: "1"
services:
  wedding-backend:
    image: ababqw123/wedding-backend:6e8746a3f88eed421b70246fe061b45c3c03ba74
    ports:
      - 8080:8080
  wedding-frontend:
    image: ababqw123/wedding-frontend:67a708e3836c02ef1eb11a8a22622ee12d9790b9
    ports:
      - 80:3000
    depends_on:
      - wedding-backend

networks:
  wedding-network:
    driver: bridge
