version: "1"
services:
  wedding-backend:
    image: ababqw123/wedding-backend:6e8746a3f88eed421b70246fe061b45c3c03ba74
    ports:
      - 8080:8080
  wedding-frontend:
    image: ababqw123/wedding-frontend:54f618b4eb8b768fb8efd228f32274bb5bda311e
    ports:
      - 80:3000
    depends_on:
      - wedding-backend

networks:
  wedding-network:
    driver: bridge
