version: "3"
services:
  wedding-backend:
    image: ababqw123/wedding-backend:29f52d6bec717f8b9f84a86f11f099b46a680031
    hostname: wedding-backend
    container_name: wedding-backend
    ports:
      - 8002:8002
    networks:
      - wedding-network      
  wedding-frontend:
    image: ababqw123/wedding-frontend:1a768efcf4e38b2886032149dfd11a1b5c644555
    hostname: wedding-frontend
    container_name: wedding-frontend
    ports:
      - 8001:3000
    depends_on:
      - wedding-backend
    networks:
      - wedding-network

networks:
  wedding-network:
    driver: bridge
