version: "1"
services:
  wedding-backend:
    image: ababqw123/wedding-backend:4b4e103da2248ba4923bb731dbb5a294742b767a
    ports:
      - 8002:8002
  wedding-frontend:
    image: ababqw123/wedding-frontend:4b4e103da2248ba4923bb731dbb5a294742b767a
    environment:
      - NEXT_PUBLIC_SERVER_URL=wedding-back-wedding-backend-1
      - NEXT_PUBLIC_MAP_TOKEN=8591044f66278fd2484621cb7140724d
    ports:
      - 8001:3000
    depends_on:
      - wedding-backend

networks:
  wedding-network:
    driver: bridge
